#pragma once

enum EEventType {
  FIRST = 0,
  ACTOR_CREATED = FIRST,
  ACTOR_DESTROYED,
  ON_COLLISION_ENTER,
  ON_COLLISION_EXIT,
  ON_ANIMATION_END,
  ON_CUSTOM_ANIM_EVENT,
  CONTACTS_UPDATED,
  PAUSE_CAMERA,
  RESUME_CAMERA,
  LAST
};